
import std/macros
import ./[
  tovalUtils,
  va_and_kw,
  tovals,
]
export tovals
import ../../Objects/[
  pyobject,
  dictobject,
  exceptions,
]


proc clinicGenAux*(hasSelf: bool, genedPureNameStr: string, def: NimNode, exported=true): NimNode =
  ## impl for pragma for proc def
  let
    originFuncName = def.name
    pureName = ident genedPureNameStr
    name = if exported: # exported
      pureName.postfix"*"
    else: pureName

  let params = def.params
  var vargs = newNimNode nnkBracket
  var beginKwOnly = false
  var kwOnlyList: seq[string]

  var callOriArgs: seq[NimNode]
  let resType = params[0]
  var start = 1
  if hasSelf: start = 2

  for i in start..<params.len:
    let
      pDef = params[i]
      pName = pDef[0].getNameOfParam
    assert pDef.len == 3, "#TODO:clinic current each param match one type (e.g. `a, b: int` shall be written as `a: int, b: int`)"
    callOriArgs.add pName
    if beginKwOnly:
      kwOnlyList.add pName.strVal
    elif pDef[0].isKwOnlyStartImpl:
      beginKwOnly = true
      kwOnlyList.add pName.strVal
    vargs.add pDef
  let
    nparam_args = ident"args"
    nparam_kwargs = ident"kwargs"
  let parserCall = PyArg_VaParseTupleAndKeywordsAs(newStrLitNode genedPureNameStr, nparam_args, nparam_kwargs, kwOnlyList, vargs)
  let nparams = nnkFormalParams.newTree resType
  let PyObjT = bindSym"PyObject"
  if hasSelf:
    let self = ident"self"
    nparams.add newIdentDefs(self, PyObjT)
    callOriArgs.insert self, 0

  nparams.add newIdentDefs(nparam_args, nnkBracketExpr.newTree(bindSym"openArray", PyObjT))
  nparams.add newIdentDefs(nparam_kwargs, PyObjT)
  let callOrigin = originFuncName.newCall callOriArgs
  let body = quote do:
    let `nparam_kwargs` = PyDictObject `nparam_kwargs`
    retIfExc `parserCall`
    `callOrigin`
  let emptyn = newEmptyNode()
  let nproc = nnkProcDef.newTree(name, emptyn, emptyn,  nparams, nnkPragma.newTree bindSym"pyCFuncPragma", emptyn, body)
  result = newStmtList(def, nproc)

proc clinicGenImplWithPrefix*(prefix: string, def: NimNode): NimNode =
  let
    originFuncName = def.name
    genedPureNameStr = prefix & originFuncName.strVal
    exported = def[0].kind == nnkPostfix
  if exported:
    assert def[0][0].strVal == "*"
  clinicGenAux(false, genedPureNameStr, def, exported)


macro clinicGenWithPrefix*(prefix: static[string], def) =
  clinicGenImplWithPrefix(prefix, def)

macro clinicGen*(name; exported: static[bool], def) =
  ## pragma for proc def.
  ## 
  ## Named after CPython's clinic
  ##
  ## main part of exportnpy, just before registering into module dict
  clinicGenAux(false, name.strVal, def, exported)
macro clinicGenMeth*(name; exported: static[bool], def) =
  clinicGenAux(true, name.strVal, def, exported)

macro bltin_clinicGen*(def) = clinicGenImplWithPrefix("builtin_", def)

proc genExcepts(excepts, body: NimNode): NimNode =
  ## helper for `clinicGenMethodOfKind` to generate exception sequence
  if excepts.len == 0:
    return body
  result = nnkTryStmt.newTree body

  for exc in excepts:
    let alias = ident "e"
    let newPyE = ident("new" & exc.strVal)
    result.add nnkExceptBranch.newTree(
      infix(exc, "as", alias),
      quote do:
        return `newPyE`(newPyStr `alias`.msg)
    )
  result = newStmtList(result)

macro clinicGenMethodOfKind*(typ; kind: static[NPyMethodKind] = NPyMethodKind.Common, exceptions: untyped = []; prc) =
  ## used for generating method with argument clinic, e.g. `PyDict_GetItem`
  ##  the method body is generated by `prc`, which is a proc that returns a NimNode
  ##  the proc takes the method name as argument, so that it can generate different body
  ##  for different methods, e.g. `PyDict_GetItem` and `PyDict_SetItem` has different body
  result = newStmtList(prc)
  let methodName = prc.name

  let prc_params = prc.params
  let args = prc_params.copyNimNode

  let call = newCall methodName
  for i in 1..<prc_params.len:
    let e = prc_params[i]
    if kind == NPyMethodKind.Common:
      if i != 1:
        args.add e
      # skip self
    else:
      args.add e

    for i in 0..<e.len-2:
      call.add e[i]
  let resType = prc_params[0]

  var body = newStmtList()
  let noRes = resType.kind == nnkEmpty
  if noRes:
    body.add quote do: result = pyNone
  else:
    body.add quote do:
      let res = `call`
      let exc = toval(res, result)
      retIfExc exc
  body = genExcepts(exceptions, body)

  var pragmas = prc.pragma
  if pragmas.kind == nnkEmpty:
    pragmas = newNimNode nnkBracket
  
  let pytyp = ident("Py" & typ.strVal & "Object")

  result.add implMethod(methodName, args, pytyp, pragmas, body, kind)

macro clinicGenMethod*(typ; prc) = getAst(clinicGenMethodOfKind(typ, NPyMethodKind.Common, [], prc))
macro clinicGenMethodRaises*(typ; exceptions; prc) = getAst(clinicGenMethodOfKind(typ, NPyMethodKind.Common, exceptions, prc))

